### ISSUE TITLE
Geo Button CSS (Mobile): Not that obvious (nice-to-fix)

### ISSUE THREAD

**Issue by JockeMedKniven** [rubenriseld/nextrecipe#91]
For a user that haven't developed our app this looks a bit confusing, does the text belong to the button or is it an uppmaning to search in your region?!:
![image](https://user-images.githubusercontent.com/112860899/235903241-b9b0efd4-dca3-42fe-9f53-cab91d9340b3.png)

**Comment by rubenriseld** [comment]
added arrow icons (temporary solution) to clarify call to action
